<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="3" ignored="0" total="4" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-07-17T00:45:52 IST" name="Accounts" finished-at="2021-07-17T00:51:07 IST" duration-ms="314255">
    <groups>
      <group name="Accounts">
        <method signature="EditAccount.editAccount(java.lang.String, java.lang.String)[pri:0, instance:salesforce.testcases.EditAccount@cb0755b]" name="editAccount" class="salesforce.testcases.EditAccount"/>
      </group> <!-- Accounts -->
    </groups>
    <test started-at="2021-07-17T00:45:52 IST" name="Accounts" finished-at="2021-07-17T00:51:07 IST" duration-ms="314255">
      <class name="salesforce.testcases.EditAccount">
        <test-method is-config="true" signature="startReport()[pri:0, instance:salesforce.testcases.EditAccount@cb0755b]" started-at="2021-07-17T00:45:52 IST" name="startReport" finished-at="2021-07-17T00:45:52 IST" duration-ms="271" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startReport -->
        <test-method is-config="true" signature="setTestDetails()[pri:0, instance:salesforce.testcases.EditAccount@cb0755b]" started-at="2021-07-17T00:45:52 IST" name="setTestDetails" finished-at="2021-07-17T00:45:52 IST" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setTestDetails -->
        <test-method is-config="true" signature="testDetailedReport()[pri:0, instance:salesforce.testcases.EditAccount@cb0755b]" started-at="2021-07-17T00:45:52 IST" name="testDetailedReport" finished-at="2021-07-17T00:45:52 IST" duration-ms="5" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDetailedReport -->
        <test-method is-config="true" signature="launchApp()[pri:0, instance:salesforce.testcases.EditAccount@cb0755b]" started-at="2021-07-17T00:45:53 IST" name="launchApp" finished-at="2021-07-17T00:45:58 IST" duration-ms="4886" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApp -->
        <test-method retried="true" signature="editAccount(java.lang.String, java.lang.String)[pri:0, instance:salesforce.testcases.EditAccount@cb0755b]" started-at="2021-07-17T00:45:58 IST" name="editAccount" data-provider="getData" finished-at="2021-07-17T00:47:08 IST" duration-ms="69640" status="SKIP">
          <params>
            <param index="0">
              <value>
                <![CDATA[JenkinsRun]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[9125784616]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.RuntimeException">
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException
at salesforce.utils.Reporter.reportStep(Reporter.java:109)
at salesforce.utils.Reporter.reportStep(Reporter.java:119)
at salesforce.pages.AccountsPage.editAccountValidation(AccountsPage.java:381)
at salesforce.testcases.EditAccount.editAccount(EditAccount.java:45)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- editAccount -->
        <test-method is-config="true" signature="closeBrowser()[pri:0, instance:salesforce.testcases.EditAccount@cb0755b]" started-at="2021-07-17T00:47:08 IST" name="closeBrowser" finished-at="2021-07-17T00:47:14 IST" duration-ms="6178" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
        <test-method is-config="true" signature="launchApp()[pri:0, instance:salesforce.testcases.EditAccount@cb0755b]" started-at="2021-07-17T00:47:14 IST" name="launchApp" finished-at="2021-07-17T00:47:16 IST" duration-ms="2473" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApp -->
        <test-method retried="true" signature="editAccount(java.lang.String, java.lang.String)[pri:0, instance:salesforce.testcases.EditAccount@cb0755b]" started-at="2021-07-17T00:47:16 IST" name="editAccount" data-provider="getData" finished-at="2021-07-17T00:48:25 IST" duration-ms="68961" status="SKIP">
          <params>
            <param index="0">
              <value>
                <![CDATA[JenkinsRun]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[9125784616]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.RuntimeException">
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException
at salesforce.utils.Reporter.reportStep(Reporter.java:109)
at salesforce.utils.Reporter.reportStep(Reporter.java:119)
at salesforce.pages.AccountsPage.editAccountValidation(AccountsPage.java:381)
at salesforce.testcases.EditAccount.editAccount(EditAccount.java:45)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:214)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- editAccount -->
        <test-method is-config="true" signature="closeBrowser()[pri:0, instance:salesforce.testcases.EditAccount@cb0755b]" started-at="2021-07-17T00:48:25 IST" name="closeBrowser" finished-at="2021-07-17T00:48:32 IST" duration-ms="6172" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
        <test-method is-config="true" signature="launchApp()[pri:0, instance:salesforce.testcases.EditAccount@cb0755b]" started-at="2021-07-17T00:48:32 IST" name="launchApp" finished-at="2021-07-17T00:48:34 IST" duration-ms="2664" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApp -->
        <test-method retried="true" signature="editAccount(java.lang.String, java.lang.String)[pri:0, instance:salesforce.testcases.EditAccount@cb0755b]" started-at="2021-07-17T00:48:34 IST" name="editAccount" data-provider="getData" finished-at="2021-07-17T00:49:45 IST" duration-ms="70622" status="SKIP">
          <params>
            <param index="0">
              <value>
                <![CDATA[JenkinsRun]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[9125784616]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.RuntimeException">
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException
at salesforce.utils.Reporter.reportStep(Reporter.java:109)
at salesforce.utils.Reporter.reportStep(Reporter.java:119)
at salesforce.pages.AccountsPage.editAccountValidation(AccountsPage.java:381)
at salesforce.testcases.EditAccount.editAccount(EditAccount.java:45)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:214)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- editAccount -->
        <test-method is-config="true" signature="closeBrowser()[pri:0, instance:salesforce.testcases.EditAccount@cb0755b]" started-at="2021-07-17T00:49:45 IST" name="closeBrowser" finished-at="2021-07-17T00:49:51 IST" duration-ms="6195" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
        <test-method is-config="true" signature="launchApp()[pri:0, instance:salesforce.testcases.EditAccount@cb0755b]" started-at="2021-07-17T00:49:51 IST" name="launchApp" finished-at="2021-07-17T00:49:54 IST" duration-ms="2987" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApp -->
        <test-method signature="editAccount(java.lang.String, java.lang.String)[pri:0, instance:salesforce.testcases.EditAccount@cb0755b]" started-at="2021-07-17T00:49:54 IST" name="editAccount" data-provider="getData" finished-at="2021-07-17T00:51:04 IST" duration-ms="70210" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[JenkinsRun]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[9125784616]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.RuntimeException">
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException
at salesforce.utils.Reporter.reportStep(Reporter.java:109)
at salesforce.utils.Reporter.reportStep(Reporter.java:119)
at salesforce.pages.AccountsPage.editAccountValidation(AccountsPage.java:381)
at salesforce.testcases.EditAccount.editAccount(EditAccount.java:45)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:214)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- editAccount -->
        <test-method is-config="true" signature="closeBrowser()[pri:0, instance:salesforce.testcases.EditAccount@cb0755b]" started-at="2021-07-17T00:51:04 IST" name="closeBrowser" finished-at="2021-07-17T00:51:07 IST" duration-ms="2165" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
        <test-method is-config="true" signature="endTestDetails()[pri:0, instance:salesforce.testcases.EditAccount@cb0755b]" started-at="2021-07-17T00:51:07 IST" name="endTestDetails" finished-at="2021-07-17T00:51:07 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endTestDetails -->
        <test-method is-config="true" signature="endReport()[pri:0, instance:salesforce.testcases.EditAccount@cb0755b]" started-at="2021-07-17T00:51:07 IST" name="endReport" finished-at="2021-07-17T00:51:07 IST" duration-ms="414" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endReport -->
      </class> <!-- salesforce.testcases.EditAccount -->
    </test> <!-- Accounts -->
  </suite> <!-- Accounts -->
</testng-results>
